"""update the experience type

Revision ID: 0156ad9bdfa5
Revises: 7b7cb9dd3f54
Create Date: 2026-01-07 18:16:06.617886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0156ad9bdfa5'
down_revision: Union[str, None] = '7b7cb9dd3f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#def upgrade() -> None:

def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume', 'experience',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               )
    # ### end Alembic commands ###

#def downgrade() -> None
def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume', 'experience',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               )
    # ### end Alembic commands ###
