"""create views on job

Revision ID: 02481726d849
Revises: 05ee05e08e85
Create Date: 2026-01-12 17:12:34.910205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02481726d849'
down_revision: Union[str, None] = '05ee05e08e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_job_user', 'applications', ['job_id', 'user_id'])
    op.add_column('jobs', sa.Column('views', sa.Integer(), nullable=False,server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'views')
    op.drop_constraint('uq_job_user', 'applications', type_='unique')
    # ### end Alembic commands ###
