"""create resume_id on application

Revision ID: 220cccc009b7
Revises: 0156ad9bdfa5
Create Date: 2026-01-08 14:52:14.926417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220cccc009b7'
down_revision: Union[str, None] = '0156ad9bdfa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#def upgrade() -> None:
def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_applications_resume_id', 'applications', 'resume', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


#def downgrade() -> None:
def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_applications_resume_id', 'applications', type_='foreignkey')
    op.drop_column('applications', 'resume_id')
    # ### end Alembic commands ###
