"""add unique constrain to job rule

Revision ID: 582300de6fb5
Revises: 02481726d849
Create Date: 2026-01-15 04:34:00.658523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582300de6fb5'
down_revision: Union[str, None] = '02481726d849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_job_rule', 'rule', ['job_id', 'criteria'])
    # ### end Alembic commands ###


def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_job_rule', 'rule', type_='unique')
    # ### end Alembic commands ###
