"""update skills type on resume

Revision ID: 7b7cb9dd3f54
Revises: 
Create Date: 2026-01-07 17:52:37.564114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7cb9dd3f54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#def upgrade() -> None:
def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume', 'skills',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
   

#def downgrade() -> None:
def downgrade():
    """Downgrade schema."""
    
    op.alter_column('resume', 'skills',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
